Update README.md
vaibhav3003/SOEN6011 pull request #1
Opened 2023-07-11 16:47 UTC by MaitryG

2023-07-11 21:50 UTC, MunjNayak approved these changes

2023-07-11 22:11 UTC, Markermav requested changes

2023-07-11 22:11 UTC, Markermav commented on README.md
>  | Khushali Parmar | 40224984 | | Frontend Developer |
add khushali github username

2023-07-11 22:11 UTC, Markermav commented on README.md
> +**1. Tracking and Reminders for Job Applications**
providing users access/login is one of the core feature; please add that

2023-07-11 22:11 UTC, Markermav commented on README.md
> +(Write the technologies used) TBD
Once Munj finds the necessary technology most feasible for us; please add it here!

2023-07-11 22:11 UTC, Markermav commented on README.md
> +**Project scope**
Write the projects scope here!

2023-07-11 22:11 UTC, Markermav commented on README.md
> +## 5. User Roles
Remove this for the time being

2023-07-11 22:11 UTC, Markermav commented on README.md
Write the project title here.

2023-07-12 00:34 UTC, naoreen approved these changes

2023-07-13 01:51 UTC, vaibhav3003 approved these changes
Looks good, approving the request.

2023-07-13 01:53 UTC, vaibhav3003 approved these changes
Looks good, approving.

2023-07-13 01:56 UTC, merged